from pathlib import Path
import json,re

ROOT=Path(__file__).resolve().parents[2]
NAME='Schlup_v_Delo_merits_1995-01-23.md'
ALL=['Stone-Zsela','Stevens',"O'Connor",'Scalia','Kennedy','Souter','Thomas','Ginsburg','Breyer']
MAJ=['Stone-Zsela','Stevens',"O'Connor",'Souter','Ginsburg','Breyer']
FIVE=['Stevens',"O'Connor",'Souter','Ginsburg','Breyer']
MIN=['Scalia','Kennedy','Thomas']
STATUTE='''(b) When after an evidentiary hearing on the merits of a material factual issue, or after a hearing on the merits of an issue of law, a person in custody pursuant to the judgment of a State court has been denied by a court of the United States or a justice or judge of the United States release from custody or other remedy on an application for a writ of habeas corpus, a subsequent application for a writ of habeas corpus in behalf of such person need not be entertained by a court of the United States or a justice or judge of the United States unless the application alleges and is predicated on a factual or other ground not adjudicated on the hearing of the earlier application for the writ, and unless the court, justice, or judge is satisfied that the applicant has not on the earlier application deliberately withheld the newly asserted ground or otherwise abused the writ.'''

HOLDINGS='''### Crime innocence invokes a demanding probability gateway

**Controlling proposition:** A prisoner seeking to overcome otherwise applicable successive or abusive habeas barriers to independent constitutional claims through innocence of the offense must present reliable new evidence and show, considering the probative record as a whole, that it is more likely than not that no reasonable, properly instructed juror would find guilt beyond a reasonable doubt. This procedural gateway does not itself establish innocence, prove any constitutional violation or shift the ultimate burden on the underlying claims; Sawyer's clear-and-convincing rule remains confined to its distinct death-eligibility setting.

**Authority:** Justice Stevens's Opinion of the Court, gateway and all-evidence portion, joined by Chief Justice Stone-Zsela and Justices O'Connor, Souter, Ginsburg and Breyer. Six of nine participants directly adopt this rule and explanation. Scalia, Kennedy and Thomas support a stricter crime-innocence quantum and would affirm.

**Controlling explanation:** The Court holds that the probability inquiry concerns innocence of the crime, not whether a concededly guilty person qualified for a death sentence. Carrier supplies the exceptional route where constitutional error probably convicted an innocent person; Sawyer preserves its different eligibility inquiry without deciding this crime question. McCleskey retains the innocence exception while enforcing finality through barriers to repetitive and abusive claims. The prisoner's burden remains demanding because the question concerns reasonable jurors considering the augmented evidentiary record, not the habeas judge's personal doubt. Kuhlmann's plurality discussion supports examination of all probative evidence, but its formulations are not converted into a separate majority holding. Jackson's trial-record sufficiency question cannot replace that task: evidence sufficient when credited at trial may have a different effect when reliable new evidence is considered with it. The State's request for one uniformly higher burden disregards the different question and the gateway's limited function. Passing this threshold permits further consideration within the governing claim rules; it does not award a writ or adjudicate innocence.

**Precedent treatment:**

- Murray v. Carrier, 477 U.S. 478: applies and specifies its probability-based crime-innocence exception without changing cause and prejudice.
- Sawyer v. Whitley, 505 U.S. 333: preserves the clear-and-convincing death-eligibility gateway and resolves the crime-innocence question that decision left open; it is not overruled or given a categorical impeachment exclusion.
- McCleskey v. Zant, 499 U.S. 467: preserves successive/abusive-claim barriers and the exceptional innocence route, without treating potential constitutional merit as sufficient to pass it.
- Kuhlmann v. Wilson, 477 U.S. 436: uses the relevant plurality discussion of the whole probative record as persuasive guidance, preserving its actual authority limit.
- Jackson v. Virginia, 443 U.S. 307: distinguishes trial-record legal sufficiency from the likely effect of an augmented record on reasonable jurors; its sufficiency rule remains intact.

**Operative evidentiary qualifications:** The court considers all relevant probative evidence, including evidence excluded at trial or becoming available afterward; trial-admissibility rules do not categorically delimit the gateway record, and even improperly admitted trial evidence may have probative force subject to reliability. The court must assess reliability and likely credibility, not accept every affidavit as true or treat the original verdict as a conclusive answer. Timing, delay and inconsistency may matter; no categorical rule excludes impeachment evidence or discredits a witness solely because the witness is a prisoner. A mere possibility of acquittal, a juror who might disagree, ordinary constitutional-merits prejudice or the reviewing judge's personal reasonable doubt is insufficient. The reasonable juror fairly considers the evidence and follows the beyond-a-reasonable-doubt instruction.

### This legal error requires a bounded remand despite the statutory refusal permission

**Controlling proposition:** The courts' use of the rejected clear-and-convincing crime gateway and reliance on the original jury's credibility function require vacatur and renewed assessment on this record; §2244(b)'s permission to refuse a qualifying subsequent petition does not itself supply an adequate independent ground to sustain that legally mistaken refusal. The Court remands through the Eighth Circuit to the District Court for application of the probability rule and a reasoned determination of necessary factual development, without deciding whether every successful innocence showing compels review, choosing a general appellate standard, or ordering a hearing, writ, retrial, release or stay automatically.

**Authority:** Justice Stevens's Opinion of the Court, statutory-refusal and remand rationale, joined by Justices O'Connor, Souter, Ginsburg and Breyer. These five directly adopt this bounded rationale. Chief Justice Stone-Zsela supplies a sixth vote for vacatur and the same gateway-assessment remand on his stated ground, without joining the separate §2244(b) analysis. No aggregation of different rationales is needed for the five-Justice holding.

**Controlling explanation:** The Court holds that discretion to refuse renewed review must be exercised under the proper governing law. McCleskey explains both the statutory permission and its qualifications; neither the label second petition nor the filing of new affidavits decides the result. The earlier federal consideration of guilt-phase ineffective assistance supplies a real legal-merits proceeding, and the lower court's additional discussion of that claim remains relevant. It does not establish an independently sufficient ground disposing of every claim despite today's legal correction. The new accounts concern the meaning of the existing videotape, identification and the interval between attack and response. The lower analysis used a stricter burden and treated credibility too categorically as the original jury's task. Those features prevent accepting it as the required probability assessment. Even assuming the ultimate refusal is discretionary, reconsideration is required here; the Court need not settle the broader discretion question. Keeney and Townsend preserve necessary factual development of properly available claims, but their predicates are not established merely by this remand. The District Court must decide what further development this gateway assessment needs.

**Precedent treatment:**

- McCleskey, 499 U.S. 467: applies the distinction between conditional consideration of new, nonabusive grounds and legally constrained refusal of successive or abusive grounds; neither permission nor exception becomes an unconditional command.
- Keeney v. Tamayo-Reyes, 504 U.S. 1, and Townsend v. Sain, 372 U.S. 293: preserve necessary factual development within their properly presented, available-claim setting and the deliberate-bypass qualification; ordinary counsel negligence alone does not forfeit a required hearing there, but no successive/abusive gateway is eliminated.
- Carrier, 477 U.S. 478: requires use of the selected crime-innocence rule before the present refusal can be sustained on its innocence assessment.

**Governing statutory terms:** Section 2244(b) provides:

> '''+STATUTE+'''

The prior-hearing alternatives are a factual evidentiary merits hearing or a legal merits hearing, each followed by a federal denial of release or other habeas remedy to a person held under a state judgment. Both unless conditions must be preserved: the later application must allege and rest on an unadjudicated factual or other ground, and the court must be satisfied that the newly asserted ground was not deliberately withheld or otherwise an abuse. New evidence is not automatically a new ground; absence of deliberate withholding does not eliminate every other kind of abuse. McCleskey requires consideration when both conditions are met and other barriers, including nonexhaustion and procedural default, are absent. The State must plead abuse with clarity and particularity by identifying prior writ history and newly raised claims and alleging abuse before the prisoner's burden arises. Cause and prejudice and the exceptional innocence route remain separate; cause and prejudice is not pressed in this review. Subsection (a)'s separate wording is not inserted into subsection (b), and no new subsection (c) predicate is established.

**Application, reservations and remedy:** The videotape was trial evidence. Green's asserted prompt call, Faherty's movement account and other later identification accounts must be assessed with the existing record; the Court finds no witness truthful or false and does not find the gateway satisfied. Proper claim classification, exhaustion, default, abuse, retroactivity and a genuinely sufficient independent merits ground retain their separate operation. Remand is not mandatory constitutional-merits review. Any necessary live testimony is for a reasoned determination under the applicable rules, not an automatic consequence of affidavits or vacatur. The merits of the suppression and ineffective-assistance claims, a freestanding innocence entitlement and any ultimate guilt determination remain undecided.'''

SEPARATE='''Chief Justice Stone-Zsela joins the Court's probability gateway and all-evidence rule and concurs in vacatur and remand. Finality is weighty, but the procedural route remains available where reliable new evidence indicates that constitutional error may have convicted an innocent person. Sawyer's death-eligibility threshold answers a different question. The lower courts must evaluate the videotape, timing and eyewitness accounts together with the trial record; passage through the gateway authorizes consideration of otherwise barred constitutional claims within their governing rules, not an innocence judgment or automatic release.

He adds guidance for the reliability inquiry. The habeas court should explain the new evidence's reliability, any independent corroboration, why the evidence was unavailable at trial, whether delay impairs credibility, whether state misconduct or ineffective counsel explains its absence, and exactly how it changes the evidentiary case the jury heard. These are nonexclusive considerations relevant to reliability and probability, not additional elements, a checklist or a new diligence requirement. He does not decide the witnesses' truthfulness or shift the underlying claims' ultimate burden. He does not join the Court's separate statutory-refusal analysis or announce a general rule governing residual refusal discretion.

Justice Kennedy dissents. Justice Thomas joins his opinion in full; Justice Scalia joins its stricter-gateway rule and application, but not its alternative discussion of the probability formulation. Kennedy would require clear and convincing evidence, on the probative record as a whole, that no reasonable juror would find guilt beyond a reasonable doubt. He proposes extending Sawyer's quantum to crime innocence; he does not claim that Sawyer already decided that question. McCleskey's treatment of abusive litigation and the exceptional nature of renewed review support the more rigorous showing in his view. The continuing identifications, uncertain timing and delayed or inconsistent accounts leave the submitted evidence insufficient under that quantum. This is not a finding that every new witness lied or that any inculpatory trial evidence invariably defeats an innocence claim.

Kennedy and Thomas additionally question the Court's predictive formulation if a probability rule is used. They would adapt Jackson's reasonable-juror approach to the enlarged evidentiary record, with limited factual inquiry where the submissions indicate that the necessary innocence showing may be made. They do not substitute the unchanged trial-record-only sufficiency test, order a hearing automatically, or establish an independent failure under a correctly applied Carrier rule. Their proposed stricter rule and application would sustain the judgment; their alternative discussion does not control.

Justice Scalia also dissents in an opinion joined by Justice Thomas. Section 2244(b), in their reading, preserves real authority to decline successive or abusive review, subject to its two qualifications and review for abuse. The earlier federal legal-merits adjudication satisfies a hearing alternative despite the lack of the now-requested factual hearing. They rely on the accepted repeat/abuse posture, the actual consideration and refusal below, and the evidentiary submission to find no abuse; they also regard the stricter gateway as correct. They do not convert permission into mandatory dismissal, classify every present claim as previously adjudicated, or find an unexamined ground deliberately withheld.

Salinger and Sanders support consideration of prior litigation within their respective settings, while McCleskey preserves the statute's conditions and judicial limits on discretion. Wong Doo shows that an adequate independent discretionary ground can sometimes preserve a judgment despite a legal error. Scalia and Thomas do not use that proposition to declare these affidavits necessarily insufficient under a correctly applied probability rule. Their statutory rationale is additional to the stricter-standard objection, but its application here shares their conclusion that the lower court used a legally proper quantum. They recognize that misconception of law or arbitrary reasons can constitute abuse and announce no unconditional affirmance should the proper gateway later be satisfied. These views do not control the remand.'''

INTERNAL='''## Event, chronological setting and procedural reach

Schlup v. Delo, No. 93-7901; October Term 1994, chunk 2. Argued October 3, 1994; merits decision January 23, 1995. The established merits channel reviews the Eighth Circuit's November 15, 1993 judgment, 11 F.3d 738, sustaining denial of the second federal §2254 application after the District Court's August 23, 1993 dismissal and September 13 Rule 59(e) denial. The judgment concerns a Missouri murder conviction and death sentence for participation in the February 3, 1984 killing of Arthur Dade. No new grant date, petition poll, jurisdictional objection or preservation finding is invented. The issue is a procedural innocence gateway to independent constitutional claims and the appropriate assessment/remedy, not a freestanding innocence merits claim.

Chief Justice Stone-Zsela and Justices Stevens, O'Connor, Scalia, Kennedy, Souter, Thomas, Ginsburg and Breyer participate at both argument and decision. All were seated before argument; nine satisfy the six-Justice quorum and five are required for a majority. No exclusion, vacancy, roster, seniority or allotment change is established. The date is the adopted supplied merits-event schedule.

The accepted successive/abusive posture and earlier federal appellate legal-merits consideration of guilt-phase ineffective assistance are preserved. They do not establish that every current ground was adjudicated, every statutory predicate is satisfied or every new ground deliberately withheld. Flowers testified to identification; Maylee's account came by deposition. The videotape was used at trial. Later Green, Faherty and inmate accounts address movement, timing and identification; they remain contested submissions. The court below emphasized delays, contradictions and two identifications, applied McCoy/Cornell's clear-and-convincing extension, treated trial credibility as the jury's function and also discussed the earlier ineffective-assistance adjudication. Heaney's dissent sought live examination. That extra merits discussion is not erased and is not converted into an independent final answer to every present claim.

## Law-entering snapshot and completed refresh

The in-world cutoff is immediately before January 23, 1995. The actual public-only supplement `entering-law/OT_1994CHUNK2_EFFECTIVE_BEFORE_1995-01-23.md` adds seven earlier-effective events: Tome (January 10), Young (January 17), and Allied-Bruce, Wolens, Asgrow, NationsBank/Ludwig and Mezzanatto (January 18). Their actual holdings and published positions were inspected or checked against this assembly's already read identical public text. They leave §2244(b), the habeas doctrines, participation, current review channel, Schlup's record and available remedies unchanged. Tome governs a distinct evidence rule and error review; Mezzanatto permits a confined knowing evidentiary waiver and supplies no intentional relinquishment here. The FAA, ADA, banking, seed and ministerial-selection holdings do not silently create a new habeas rule. Same-day McKennon supplies no entering law. No anticipated decision, later doctrine, AEDPA provision, future execution fact or later evidence enters.

The complete former §2244(b), current through January 4, 1995 with no intervening change admitted, has both hearing alternatives and both conjunctive unless qualifications stated in the controlling holdings below. McCleskey controls conditional consideration of new, nonabusive grounds absent other barriers, particularized abuse pleading, the prisoner's responsive burden and judicial limits on refusal. Carrier supplies crime-innocence access; Kuhlmann's all-evidence discussion remains plurality reasoning; Jackson is trial-record legal sufficiency. Neither a bare second-petition label nor new affidavits alone decides availability.

The register “Capital eligibility innocence as a gateway to barred habeas claims,” present operation effective Sawyer, June 22, 1992, retains the five-Justice clear-and-convincing death-eligibility rule and its express crime-innocence reservation. Keeney, May 4, 1992, preserves Townsend's deliberate-bypass limitation and necessary factual development of properly presented available claims; ordinary counsel negligence does not itself defeat that distinct hearing duty. It does not abolish successive/abusive/default rules. Herrera, January 25, 1993, has only a majority-supported record-specific insufficiency holding, no uniform freestanding burden. Delo v. Blair, July 21, 1993, is an equal division without precedent. The register “Preserved protected-silence error on federal habeas review,” effective Brecht, April 21, 1993, applies Chapman to the preserved Doyle claim, not a gateway standard. “Capital habeas counsel before a merits petition and discretionary stays,” effective McFarland, June 30, 1994, provides counsel and individualized preparatory authority, not an automatic hearing, innocence gate or stay. No historical contrary Keeney, Brecht or broader Herrera rule is imported.

## Stone fixed core, revalidation and exact joins

The parent operator confirms user approval of the unchanged Section II. Stone expressly vacates the Eighth Circuit judgment and remands for assessment of all reliable old and new evidence under Carrier's more-likely-than-not/no-reasonable-juror rule. The gateway permits adjudication of otherwise barred claims only within the governing procedural rules and creates no innocence judgment, freestanding cause, immediate release or shift of merits burdens. He preserves Sawyer's distinct eligibility standard and the nonexclusive reliability considerations stated in his concurrence. Those considerations remain reasoning about reliability/probability, not new mandatory elements or diligence requirements.

Stone joins the Court's gateway/all-evidence portion and the vacatur/remand judgment. His text does not choose a new general §2244(b) residual-discretion rule or independently adopt the supplemental statutory-refusal theory. He therefore does not join that separate rationale, which has five direct Associate votes. His concurrence states the approved evidentiary guidance and limited procedural ground without adopting either residual-discretion theory. This respects his express result without filling a missing statutory preference. No fallback is invoked: the supplement expressly resolves the same petition's gateway and disposition, and the added defense of that judgment is not an unaddressed claim, count or docket component. No new substantive narrowing or alternative ground is attributed to him. The actual earlier-effective law, corrected statutory alternatives and bounded remand change none of his approved rule, result, limits or factual premises.

## Assignment, opinion form and final compatibility

Stone is in the vacatur majority and assigns the opinion to Stevens under Engine §8. Stevens's Carrier concurrence and Keeney position support a focused innocence-gateway exposition; historical authorship is not the assignment authority. The gateway/all-evidence part has six direct votes: Stevens, Stone, O'Connor, Souter, Ginsburg and Breyer. The statutory-refusal/remand rationale has five: Stevens, O'Connor, Souter, Ginsburg and Breyer. Stone adds the sixth judgment vote without an unapproved statutory join. O'Connor's minimum reservation about general discretion and appellate review is included in the Court's rationale; no redundant separate writing is required to preserve it.

Kennedy writes the stricter-standard dissent, joined by Thomas in full and Scalia on the strict rule/application only. Kennedy's and Thomas's alternative modified all-evidence Jackson objection is not imputed to Scalia. Scalia writes the additional statutory-discretion dissent, joined by Thomas; Kennedy does not join it. These exact scope distinctions implement frozen commitments rather than infer substantive joins from common judgments. No Court proposition depends on a Marks synthesis, and no final Associate position changes after reconciliation.

## Adaptive audit annex

The immutable sequence is the original group-B neutral/commitment handoff; first group-B reconciliation with a stopped statutory subissue; clean `OT_1994CHUNK2_SCHLUP_NEUTRAL_REFRESH.md`; independent `OT_1994CHUNK2_SCHLUP_COMMITMENTS_REFRESH.md`; public-law check; then `OT_1994CHUNK2_SCHLUP_RECONCILED_FINAL.md`. The latter prospectively replaces only the incomplete Schlup reconciliation. Stone enters after that final handoff. Clean modeling received no Stone or comparator; reconciliation received the comparator but no Stone. General model knowledge cannot be erased. No claim is made that this assembly was itself blind, and no frozen artifact is rewritten.

| Associate | Original and refreshed independent position | Final reconciliation and sufficient support | Final exact compatibility |
|---|---|---|---|
| Stevens | Original and refreshed: Carrier probability, vacate/remand; refreshed statute rejects permission alone as adequate affirmance. | Retained. His Carrier concurrence, McCleskey dissent join and simulated Keeney join support exceptional access and necessary development within actual predicates; governing McCleskey still controls. | Authors both Court portions. No automatic affidavit acceptance, merits review or hearing. |
| O'Connor | Original and refreshed: probability, vacate/remand; apply actual §2244(b) alternatives and qualifications. | Retained. Carrier authorship, McCleskey majority join and simulated Keeney authorship support the rule. The minimum common remand rests on legal error while reserving general discretion and review standard. | Joins both portions with those express reservations; ordinary merits prejudice or personal doubt is insufficient. |
| Scalia | Original: strict quantum/affirm, statutory ground initially unmodeled. Refreshed: strict/affirm but declined a distinct statutory ground, correctly rejecting permission alone. | Final reconciliation restores additional permission-plus-actual-no-abuse ground. His McCleskey and simulated Sawyer/Herrera joins, unchanged statute, prior legal merits and accepted repeat/abuse posture support it; the historical ground was not permission alone. | Joins Kennedy's strict rule/application, not the alternative probability discussion; authors statutory dissent joined by Thomas. No hypothetical Carrier insufficiency finding or mandatory-dismissal rule. |
| Kennedy | Initially probability/remand; first reconciliation corrected to strict/affirm. Fresh model independently selected strict/affirm. | Retained after refresh. His McCleskey and simulated Sawyer authorship supports extending the quantum to the open crime question; his Keeney join concerns available claims and does not displace repeat barriers. | Authors strict dissent; narrower modified all-evidence Jackson discussion retained. Does not join Scalia's additional statutory ground. |
| Souter | Original and refreshed: probability/remand with independent barriers preserved. | Retained. McCleskey and simulated Sawyer joins preserve eligibility's distinct scope; Carrier supplies the crime branch. McFarland supplies no new gate or stay. | Joins both Court portions; legal-rule error requires this reconsideration without universal review or automatic hearing. |
| Thomas | Original: strict/affirm, statutory ground unmodeled. Refreshed: strict/affirm, declining a separately sufficient statutory ground. | Final reconciliation restores the same bounded statutory ground as Scalia. His simulated Sawyer/Herrera positions and unchanged statutory/record premises support it; no McCleskey personal join is invented because he was not then seated. | Joins Kennedy's full dissent and Scalia's statutory dissent; no new constitutional merits finding or independent correctly-applied-Carrier insufficiency result. |
| Ginsburg | Original and refreshed: probability/remand, statute not curing the identified legal error. | Retained. Independently applies Carrier and the actual Sawyer reservation; McFarland supports meaningful preparation only within its conditions. No predecessor's position supplies her vote. | Joins both Court portions; preserves claim rules, disputed reliability and individualized factual development. |
| Breyer | Original and refreshed: probability/remand, statutory permission and conditions preserved. | Retained. Independently applies Carrier/McCleskey and Kuhlmann at its plurality level. His Tome dissent creates no habeas rule and Blackmun's position is not inherited. | Joins both Court portions; neither affidavits alone nor existing inculpatory testimony mechanically decides the inquiry. |

The refreshed model's omission of Scalia/Thomas's statutory rationale was corrected in reconciliation before Stone entered. No concrete changed premise supported abandonment of their fuller historical ground: statutory text, accepted procedural posture and relevant pre-divergence law remain, while simulated Keeney protects only otherwise available claims and Sawyer retains independent barriers. This is no finding of a newly established claim-by-claim abuse history. Their statutory application still shares their acceptance of the stricter quantum and does not survive every possible contrary legal or factual finding automatically. Kennedy's earlier provisional departure likewise lacked a sufficient changed premise after examining the exact simulated Keeney/Sawyer limits. All eight final Associate judgments match their historical judgment positions; their legal accounts nevertheless preserve the different simulated scope of earlier holdings.

**Historical departure:** The judgment is 6–3 rather than the historical 5–4 because Stone's approved Carrier probability position supplies an additional vote for vacatur in place of the historical Chief's stricter-gateway affirmance. No changed Associate premise, vote or additional statutory join is invented: Stevens, O'Connor, Souter, Ginsburg and Breyer retain remand; Scalia, Kennedy and Thomas retain affirmance, with Scalia and Thomas alone additionally adopting the bounded statutory-refusal rationale.

## Continuity, source map and validation status

The probability crime gateway and bounded remand rationale operate from January 23, 1995. The underlying constitutional merits, factual innocence, hearing need and separate claim barriers remain unresolved. The Eighth Circuit must return the matter to the District Court for the directed assessment. No immediate release, retrial, writ, new stay, filing deadline, institutional change or outside event is entered. All published noncontrolling positions appear verbatim in the continuity section below and in Public Projection Separate Writings; no additional published proposition is withheld from the sanitized workspace handoff.

The [Eighth Circuit opinion and dissent](https://openjurist.org/11/f3d/738) supplies dates, denial, legal standard, contested evidence and additional merits discussion. The [primary briefs/appendix collection](https://archive.org/details/micro_IA40385013_0538), petitioner 05 and respondent 06, supplies the reviewed factual, argument and remedy passages, including that cause/prejudice is no longer pressed. The initial digest reviewed pertinent portions, not the entire appendix; this assembly does not claim independent full litigation-file review. The clean refresh retrieved and verified [official 1994 §2244](https://uscode.house.gov/view.xhtml?edition=1994&num=0&req=granuleid%3AUSC-1994-title28-section2244), preserving the source at tmp/neutral_refresh_sources/2244_1994_official.txt, and checked McCleskey's statutory discussion. The complete [official historical report](https://tile.loc.gov/storage-services/service/ll/usrep/usrep513/usrep513298/usrep513298.pdf), research/reconcile_b/298.pdf and .txt, was read in reconciliation for comparator dates, scope and writings, not as entering law or automatic assignment. Original/rerefreshed packets and final reconciliation fix the source boundary. No missing source blocks this bounded gateway ruling; new definitive credibility, claim classification or independent merits findings would require the actual supporting record and renewed scoped validation.

Research cutoff: immediately before January 23, 1995. Statutory compilation cutoff January 4, 1995; no intervening amendment admitted. Retrieval/assembly September 28, 2026 is internal provenance only. The actual seven-event refresh was compared before preservation; McKennon is excluded despite its same-day record's existence. Assembly preserves final frozen commitments, fixed Stone scope, source qualifications, both statutory hearing alternatives, both unless clauses and all remedy limits. The deterministic script checks initial four labels, exactly eleven ordered public blocks, internal/public Holdings identity, 120–200-word explanations and named vote/holding arithmetic. `OT_1994CHUNK2_VOTES_SCHLUP.json` records the final arithmetic separately, avoiding duplicate entries in group B data. Parent/operator term-wide checks, generated render input, ledger/manifest/continuity updates remain for completion; none is claimed performed here. This initial Record supersedes no completed event. Its file is preserved for operator incorporation with legal effect January 23, 1995. No Git command, Git-dependent script, Git commit or Render is performed or claimed.

## Published noncontrolling positions retained for continuity

'''+SEPARATE

PUBLIC={
 'Event': 'Schlup v. Delo, No. 93-7901. Argued October 3, 1994; merits decision January 23, 1995. On writ of certiorari to the Eighth Circuit, reviewing 11 F.3d 738, which sustained denial of a second federal habeas application without the requested evidentiary hearing. Schlup offers crime-innocence evidence as a gateway to otherwise barred ineffective-assistance and suppression claims arising from his conviction for participation in a prison murder. The questions concern the gateway quantum, the augmented evidentiary inquiry, statutory refusal authority and the proper remand. Render form: full; judgment, gateway rationale and statutory-refusal rationale have distinct coalitions and partial joins.',
 'Participation': "Chief Justice Stone-Zsela and Justices Stevens, O'Connor, Scalia, Kennedy, Souter, Thomas, Ginsburg and Breyer participated at argument and decision.",
 'Public Action': 'The Court vacates the Eighth Circuit judgment and remands with instructions to return the matter to the District Court for proceedings under the probability crime-innocence gateway. It does not find Schlup innocent or find the gateway satisfied.',
 'Judgment & Remedy': "| Judgment component | Disposition and vote | Supporting Justices | Opposing Justices | Remedy |\n|---|---|---|---|---|\n| Rejection of the innocence gateway and denial of renewed review | Vacate and remand, 6–3 | Stone-Zsela, Stevens, O'Connor, Souter, Ginsburg, Breyer | Scalia, Kennedy, Thomas | Eighth Circuit to remand to District Court for the correct whole-record probability assessment and a reasoned determination of needed factual development. |\n\nThe three dissenters would affirm under the stricter crime-innocence showing; Scalia and Thomas also support a bounded statutory-discretion ground. The mandate orders no automatic hearing, constitutional-merits adjudication, retrial, writ, release or stay.",
 'Opinion Topology': "| Writing | Author | Joined by | Relationship to judgment | Scope joined |\n|---|---|---|---|---|\n| Opinion of the Court | Stevens | O'Connor, Souter, Ginsburg, Breyer in full; Stone-Zsela in the gateway/all-evidence portion only | Vacatur and remand | Six directly support the gateway rule; five directly support the statutory-refusal/remand rationale. Stone supports the same judgment on his stated ground. |\n| Concurrence in part and in the judgment | Stone-Zsela | No other Justice | Joins gateway portion and vacatur/remand | Adds nonexclusive reliability guidance; no join to separate §2244(b) analysis. |\n| Dissent | Kennedy | Thomas in full; Scalia in the strict-standard rule and application only | Would affirm | Scalia does not join the alternative modified-Jackson discussion. |\n| Separate dissent | Scalia | Thomas | Would affirm on an additional statutory-refusal ground | Permission plus actual no-abuse assessment; retains the stricter-standard premise and supplies no independent correctly-applied-Carrier insufficiency finding. |",
 'Holdings': HOLDINGS,
 'Precedent Treatment': 'Carrier supplies the crime-innocence route, while Sawyer retains its distinct clear-and-convincing eligibility rule. McCleskey\'s statutory qualifications, abuse pleading, cause/prejudice framework and innocence exception remain. Kuhlmann\'s relevant discussion retains plurality force, and Jackson\'s trial-record sufficiency rule remains separate. Keeney and Townsend govern necessary factual development within their actual available-claim conditions. Herrera retains only its record-specific insufficiency holding, Delo v. Blair supplies no precedent from equal division, Brecht remains a preserved-error merits decision, and McFarland supplies no automatic gateway or stay. No prior controlling holding is overruled.',
 'Law After Decision': 'Effective January 23, 1995, reliable new evidence of crime innocence is assessed with the whole probative record under the more-likely-than-not/no-reasonable-juror gateway. The prisoner retains that demanding burden and must separately establish any underlying constitutional claim. Section 2244(b)\'s qualified permission, lawful independent barriers and necessary factual-development rules remain; the Court decides neither a universal mandatory-review rule after a successful showing nor a general appellate standard for refusal. The judgment corrects the legal inquiry and creates no freestanding innocence remedy.',
 'Separate Writings': SEPARATE,
 'Procedure After Action': 'The Eighth Circuit judgment is vacated. That court must remand to the District Court for the proper gateway assessment, including a reasoned decision about factual development. The existing videotape and new timing and identification accounts must be considered together; the Court predetermines no credibility finding, gateway success or hearing requirement. Otherwise barred constitutional claims may proceed only within the gateway and other governing conditions, and passing the gateway proves none of their merits. Supreme Court review ends; the habeas proceeding continues below without an automatic writ, retrial, release or stay.',
 'Source Notes': 'The [Eighth Circuit opinion, 11 F.3d 738](https://openjurist.org/11/f3d/738), supplies the lower judgment, separate dissent and disputed evidentiary account. The [briefs and appendix collection](https://archive.org/details/micro_IA40385013_0538) supports the reported claims and requested relief. The quotation of §2244(b) is verified against the [official 1994 Code, laws in effect January 4, 1995](https://uscode.house.gov/view.xhtml?edition=1994&num=0&req=granuleid%3AUSC-1994-title28-section2244). [McCleskey, 499 U.S. 467](https://www.law.cornell.edu/supremecourt/text/499/467), supplies its conditional-duty and abuse discussion. The affidavits remain contested submissions, and no later investigation is treated as part of the record without its proper submission.'
}
BLOCKS=['Event','Participation','Public Action','Judgment & Remedy','Opinion Topology','Holdings','Precedent Treatment','Law After Decision','Separate Writings','Procedure After Action','Source Notes']
assert list(PUBLIC)==BLOCKS
text='''**Case and dockets:** Schlup v. Delo; No. 93-7901.
**Event and date:** Merits decision, 1995-01-23; October Term 1994, chunk 2.
**Result:** Eighth Circuit judgment vacated and remanded, 6–3, for the probability crime-innocence gateway; no automatic hearing, writ or innocence determination.
**Version / lineage:** Initial Canonical Decision Record; supersedes no completed adjudication. Final refreshed reconciliation resolves the previously uncommitted statutory subissue. File preservation only under the no-Git instruction; no repository commit is claimed.

'''+INTERNAL+'\n\n## Controlling holdings\n\n'+HOLDINGS+'\n\n## Public Projection\n\n'+'\n\n'.join('## '+k+'\n\n'+v for k,v in PUBLIC.items())+'\n'
pub=text.split('## Public Projection\n\n',1)[1]
assert re.findall(r'^## (.+)$',pub,re.M)==BLOCKS
assert text.split('## Controlling holdings\n\n',1)[1].split('\n\n## Public Projection',1)[0]==pub.split('## Holdings\n\n',1)[1].split('\n\n## Precedent Treatment',1)[0]
lengths=[len(s.split()) for s in re.findall(r'\*\*Controlling explanation:\*\* (.*?)(?=\n\n\*\*Precedent treatment:)',HOLDINGS,re.S)]
assert all(120<=n<=200 for n in lengths),lengths
for label,line in zip(['**Case and dockets:**','**Event and date:**','**Result:**','**Version / lineage:**'],text.splitlines()):
    assert line.startswith(label)
assert set(MAJ).isdisjoint(MIN) and set(MAJ)|set(MIN)==set(ALL)
assert len(MAJ)==6 and len(FIVE)==5 and len(MIN)==3
assert not any(s in pub for s in ['Git','historical comparator','Section II','simulated','AEDPA','McKennon','approved'])
draft=ROOT/'freeze'/'drafts'/NAME
draft.write_text(text,encoding='utf-8')
vote={'filename':NAME,'participants':ALL,'nonparticipants':[],'components':[{'label':'vacatur and bounded gateway remand','support':MAJ,'oppose':MIN,'count':'6-3'}],'writings':[{'author':'Stevens','joins':FIVE[1:],'scope':'full; Stone-Zsela additionally joins gateway/all-evidence portion only'},{'author':'Stone-Zsela','joins':[],'scope':'concurrence in gateway part and judgment; reliability guidance, no §2244(b) interpretation'},{'author':'Kennedy','joins':['Thomas'],'partial_joins':[{'justice':'Scalia','scope':'strict rule and application only; excludes modified-Jackson alternative'}],'scope':'strict gateway and application; bounded modified-Jackson alternative'},{'author':'Scalia','joins':['Thomas'],'scope':'additional §2244(b) discretion and no-abuse rationale with strict-rule premise'}],'holding_coalitions':[{'label':'probability crime gateway and all-evidence method','support':MAJ},{'label':'§2244(b) does not independently sustain actual refusal; bounded remand rationale','support':FIVE}],'separate_ground_coalitions':[{'label':'strict gateway affirmance','support':MIN},{'label':'additional statutory-refusal affirmance','support':['Scalia','Thomas']}]}
(ROOT/'freeze'/'OT_1994CHUNK2_VOTES_SCHLUP.json').write_text(json.dumps(vote,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(NAME,'PASS; controlling-explanation word counts',lengths)
