from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[2]
DRAFTS = ROOT / 'freeze' / 'drafts'
BLOCKS = ['Event', 'Participation', 'Public Action', 'Judgment & Remedy', 'Opinion Topology', 'Holdings', 'Precedent Treatment', 'Law After Decision', 'Separate Writings', 'Procedure After Action', 'Source Notes']
VOTES = []

def record(filename, identity, result, internal, public, vote):
    assert list(public) == BLOCKS
    text = f'**Case and dockets:** {identity}\n**Event and date:** Merits decision, 1995-01-18; October Term 1994, chunk 2.\n**Result:** {result}\n**Version / lineage:** Initial Canonical Decision Record; supersedes no completed adjudication. File preserved under the user\'s no-Git instruction; no Git operation or repository commit is claimed.\n\n'
    text += internal.strip() + '\n\n## Controlling holdings\n\n' + public['Holdings'] + '\n\n## Public Projection\n\n'
    text += '\n\n'.join('## ' + k + '\n\n' + v.strip() for k,v in public.items()) + '\n'
    (DRAFTS / filename).write_text(text, encoding='utf-8')
    vote['filename'] = filename
    VOTES.append(vote)

COMMON_STATUS = '''The assembly uses the immutable validated neutral, independent-commitment and reconciled group-B handoffs. Stone enters only in this assembly. Earlier neutral-source exposure, clean revalidation and staged-context provenance are retained in the upstream handoffs; no broader claim of erased general model knowledge is made. No associate commitment is changed during assembly. Assignment and final compatible joins are Engine inferences, not assertions about historical drafting or private conference dialogue.

Research cutoff: immediately before January 18, 1995. Pre-decision statutory and litigation facts are distinguished from the present adjudication. The independent packet reports only limited underlying merits-brief review and does not claim a full independent appendix review. The reconciliation context downloaded and read the complete official report for comparator purposes; that report supplies no earlier in-world law. The source limits stated below remain operative. No new external follow-on event is admitted.

Chronology validation: the actual public-law supplement `entering-law/OT_1994CHUNK2_EFFECTIVE_BEFORE_1995-01-18.md` was read and compared before Record preservation. Tome, effective January 10, construes Rule 801(d)(1)(B)'s premotive condition and preserves separate admission and error-review requirements; Young, effective January 17, supplies a claim-specific ministerial-selection defense and distinguishes merits from substantial-federal-question jurisdiction. Neither changes the ADA, National Bank Act, FAA, participation, established merits route, record or available remedy here. Neither creates a general evidentiary, contractual or agency rule altering the frozen alternatives. Stone's fixed core likewise encounters no material changed premise. The frozen positions therefore stand without a clean-stage return. These uncoordinated January 18 matters use the common pre-January-18 baseline. No Asgrow, Mezzanatto, Wolens, NationsBank or Allied-Bruce decision of January 18 supplies entering law to another. The date is an adopted merits-event scheduling premise, not an imported historical grant or poll.

Preservation and validation: assembly has checked the actual earlier-effective public law, fixed-core compatibility, source bounds, component vote arithmetic, final joins and exact holding/projection identity. The authoritative file is preserved under records with its natural filename on September 28, 2026, for operator incorporation with legal effect January 18, 1995. Exact component vote, opinion-join and controlling-coalition arithmetic is recorded in freeze/OT_1994CHUNK2_VOTES_B.json. No term-wide check, ledger rebuild, manifest rebuild, Render Input generation, repository commit or current-workspace update is claimed by this assembly. Parent/operator validation and those coordinated projections remain required before declaring the chunk complete. No Git command or Git-dependent script was run.'''

W_HOLDINGS = '''#### State consumer-fraud standards governing these airline benefits are preempted

**Controlling proposition:** The Airline Deregulation Act's transaction-period §1305(a)(1) preempts application of the Illinois Consumer Fraud and Deceptive Business Practices Act to the pleaded devaluation of earned airline-travel awards through changed redemption restrictions, because that claim enforces a state-imposed substantive standard directly related to airline rates and services. General applicability, a damages remedy and the general §1506 savings clause do not avoid that express prohibition; materially different duties with only tenuous, remote or peripheral connections remain outside this ruling.

**Authority:** Justice Ginsburg's Opinion of the Court, consumer-fraud portion, joined by Chief Justice Stone-Zsela and Justices Kennedy, Souter and Breyer. Five of the eight participating Justices directly adopt the rule and explanation. Justices O'Connor and Thomas also vote to preempt this claim on their separate broader ground; Justice Stevens dissents on this component.

**Controlling explanation:** The Court holds that the challenged award restrictions concern the price and availability of airline transportation. Capacity controls govern how many seats passengers may obtain at an award level; the alleged restrictions on use of earned credits govern what travel those credits purchase. Morales supplies the rule that a generally applicable law can regulate airline rates and services when its application has the required connection. The Illinois court's description of frequent-flyer benefits as peripheral does not answer that direct relation. A damages action may enforce the same substantive command as prospective regulation, so the form of relief does not remove the conflict. Section 1506 preserves remedies outside the specific prohibition rather than undoing it. Cipollone's distinct cigarette provisions require attention to the duty and wording at issue, not a universal exception for claims called fraud. The Court decides this pleaded challenge without resolving the disputed retroactive application of particular blackout dates or declaring every airline deception claim preempted.

**Precedent treatment:**

- Morales v. Trans World Airlines, Inc., 504 U.S. 374: applies the controlling connection-or-reference rule and the specific-preemption/general-savings distinction to these award restrictions; its separate fare-marketing effects holding remains confined to that package, and its remote-effects reservation remains.
- Cipollone v. Liggett Group, Inc., 505 U.S. 504: distinguishes its clause-specific preservation of general intentional falsehood; that cigarette holding supplies no universal airline-fraud exemption and retains its own scope.

#### An airline's actual voluntary bargain remains enforceable

**Controlling proposition:** Section 1305(a)(1) does not preempt ordinary court enforcement of an airline's self-imposed contractual obligations, including ordinary contract remedies, when the claim is confined to the undertaking the parties actually made. Courts may use ordinary contract law to identify and enforce that undertaking, but may not enlarge or reform it through a state policy external to the agreement; the pleaded contract claims survive dismissal only within that boundary.

**Authority:** Justice Ginsburg's Opinion of the Court, contract portion, joined by Chief Justice Stone-Zsela and Justices Stevens, Kennedy, Souter and Breyer. Six of eight participants directly adopt this rationale; no synthesis of narrower separate opinions is required. Justices O'Connor and Thomas dissent on this component.

**Controlling explanation:** The Court holds that enforcing the parties' own bargain differs from prescribing its substantive terms. The airline chooses the obligation; ordinary adjudication determines what it promised and supplies the usual remedy for a proved breach. The Act's prohibition on state enactment or enforcement of governing legal standards, read with its savings clause, leaves room for that private ordering. Cipollone supplies a useful distinction between a voluntarily undertaken promise and a duty imposed by the State, although the airline clause requires its own construction. The contrary position correctly observes that contracts depend on law for enforcement. That observation does not make every privately chosen term a state-prescribed airline policy. The limitation is therefore substantive: a contract label cannot preserve an external fairness requirement. American's reservation of authority to alter its program may defeat the claimed promise, but its reach must be determined below. No binding promise protecting earned credits, breach, reliance, causation or damages is found here; the Court orders only the confined contract proceeding.

**Precedent treatment:**

- Cipollone, 505 U.S. 504: extends the voluntary-source distinction by analogy to this independently construed airline clause; its narrower warranty ground does not become a blanket common-law exemption.
- Morales, 504 U.S. 374: preserves preemption of state-prescribed airline terms while resolving the contract-enforcement question that Morales left open; neither that case's injunction nor its fare-marketing effects holding decides the actual bargain here.
- Norfolk & Western Railway Co. v. American Train Dispatchers Association, 499 U.S. 117: distinguishes the dependence of a contract on law for enforceability from the source of the substantive obligation under this statute; its construction of the distinct railroad immunity provision is undisturbed.

**Limits and questions not reached:** The lower courts must determine the actual agreement, including whether American reserved authority to alter already earned credits, applicable ordinary defenses and any proved remedy. Good-faith and implied-term tools may identify the agreement but may not reintroduce external state rate policy; no particular such theory, punitive award or nonflight-benefit claim is adjudicated. The earlier rejection of injunctive relief remains undisturbed. No final fraud or contract liability, amount or precise retroactive blackout application is decided.'''

W_SEPARATE = '''Justice Stevens concurs in the contract judgment and joins the Court's contract reasoning, but dissents from preemption of the consumer-fraud claim. He distinguishes ordinary private redress for deception from the binding fare-marketing requirements addressed in Morales, which supplies the governing airline precedent but did not decide every application of a general fraud law. His approach is consistent with Cipollone's preservation of intentional material falsehood and voluntary promises under the provisions there construed. He would permit both damages branches to proceed, without adopting a finding that American deceived its customers or that the asserted contract existed. His fraud position does not control.

Justice O'Connor concurs in the judgment preempting consumer-fraud damages and dissents from preservation of contract damages. Justice Thomas joins her statutory-enforcement analysis and proposed reversal of both branches, but does not join her separate discussion of adherence to statutory precedent. They read the Act's prohibition on state enforcement as reaching legal enforcement of contract obligations directly related to airline rates and services. Norfolk & Western explains that contracts depend on law for enforceability; on their reading, the promise's private source cannot sever that connection. Cipollone used materially different language and therefore does not require the Court's exception. Their position reserves genuinely remote claims and does not establish universal airline immunity. O'Connor alone further explains that adherence to Morales's settled statutory construction is compatible with disagreement over how to draw today's contract boundary. Neither Justice adopts the Court's contract rationale, and Thomas's join extends no further than the identified substantive analysis.'''

W_JUDGMENT = '''| Judgment component | Disposition and vote | Supporting Justices | Opposing Justices | Remedy |
|---|---|---|---|---|
| Illinois Consumer Fraud Act damages | Reverse survival against preemption, 7–1 | Stone-Zsela, O'Connor, Kennedy, Souter, Thomas, Ginsburg, Breyer | Stevens | This pleaded branch is preempted. |
| Contract damages confined to the airline's undertaking | Affirm denial of dismissal to that extent, 6–2 | Stone-Zsela, Stevens, Kennedy, Souter, Ginsburg, Breyer | O'Connor, Thomas | Remand for determination and enforcement of the actual bargain, without external state-policy enlargement. |

The Illinois Supreme Court judgment is affirmed in part and reversed in part, and the cause is remanded. Its categorical peripheral-program rationale is rejected. The earlier ruling rejecting injunctive relief remains undisturbed. The Court grants no damages, reinstates no injunction and decides no final breach or fraud question.'''

W_TOPOLOGY = '''| Writing | Author | Joined by | Relationship to judgment | Scope joined |
|---|---|---|---|---|
| Opinion of the Court | Ginsburg | Stone-Zsela, Kennedy, Souter, Breyer in full; Stevens in the neutral factual/posture account and contract portion only | Supports fraud preemption and confined contract survival | Five join the consumer-fraud rationale; six join the contract rationale. Stevens does not join the fraud-preemption discussion or its account of Morales's application. |
| Concurrence in part and dissent in part | Stevens | No other Justice | Agrees on contract; would preserve fraud damages also | Separate fraud analysis; contract join remains as stated above. |
| Concurrence in the judgment in part and dissent in part | O'Connor | Thomas in the statutory-enforcement analysis and disposition, excluding the separate statutory-precedent discussion | Agrees on fraud preemption; would preempt contract damages also | Neither joins the Court's contract rationale; the statutory-precedent discussion is O'Connor's alone. |'''

W_INTERNAL = '''## Event, participation and entering law

American Airlines, Inc. v. Wolens, No. 93-1286. Argument November 1, 1994; merits decision January 18, 1995. Established merits review of the Illinois Supreme Court's December 16, 1993 interlocutory judgment, 157 Ill. 2d 466, 626 N.E.2d 205, following 147 Ill. 2d 367, 589 N.E.2d 533. The certified dismissal issue separately presents Consumer Fraud Act and contract damages after the injunction branch was rejected. The merits channel is admitted; no new grant, petition poll, finality objection or concession is invented. State proceedings remain interlocutory after this decision.

Stone-Zsela, Stevens, O'Connor, Kennedy, Souter, Thomas, Ginsburg and Breyer participate at argument and decision. Scalia takes no part; no reason is established. Eight participants meet the six-Justice quorum; five votes form a judgment or proposition majority. The seated OT1994 roster and seniority otherwise remain unchanged.

The entering-law slice supplies the controlling Morales connection/reference rule and its separate confined fare-marketing effects ground; the register “Airline rates, routes and services under the express preemption clause” operates from June 1, 1992. Its remote-effects and unthreatened-claim reservations remain. The register “Cigarette-labeling preemption by statutory period and predicate duty,” effective Cipollone, June 24, 1992, supplies the narrower voluntary-warranty and intentional-falsehood holdings without a whole-opinion majority or general common-law exemption. O'Melveny's FDIC common-law limits do not create replacement federal airline contract law. Brown's text-first review and Transcon's confined public credit-rule injunction do not answer the distinct ADA question. Bancorp supplies no live mootness issue here.

Use transaction-period 49 U.S.C. App. §§1305(a)(1) and 1506 for the May 1988 pleaded conduct. The 1994 recodification does not change the merits rule. The untriggered Alaska exclusion is qualified by noncharter transportation under a §41102 certificate; the airport-proprietor provision preserves qualifying public proprietors' powers. The later separate property paragraph preserves motor-vehicle safety, size/weight/hazard-based highway controls, motor-carrier insurance/self-insurance financial responsibility and household-goods transportation, and does not limit passenger paragraph (1). Those provisions do no work in this passenger-award case and furnish no generalized airline immunity.

## Stone fixed core and final compatibility

The parent operator confirms the user's approval of Section II as written; the runtime label's earlier preparation status does not withdraw that approval. Stone reaches both preemption questions, reverses the fraud branch, affirms the confined contract branch and remands. His core distinguishes external substantive consumer standards from the actual private undertaking, preserves ordinary remedies and contract interpretation, and permits good-faith or implied-term tools only to identify that agreement without external-policy enlargement. The Court opinion preserves all of those limits without adjudicating any unpresented specific implied-term claim. He joins Ginsburg's opinion in full. No standing fallback is used, no fixed ground is narrowed or exchanged, and no additional substantive Stone ground is added. Revalidation against the corrected interlocutory posture, reserved contract construction and prior injunction rejection reveals no changed controlled component; the pre-January-18 comparison remains separately identified in status.

## Assignment, judgment and continuity

Stone belongs to both judgment majorities and assigns both components to Ginsburg under Engine §8. Her independent treatment of the full clause and ordinary contract incidents is suited to retaining the component coalitions. This assignment is an assembly choice, not an importation of historical authorship. Her fraud portion has five exact rationale joins including its author; the contract portion adds Stevens for six. O'Connor and Thomas concur only in the fraud judgment and dissent on contract; Stevens does the reverse on the fraud component. The tables in the Public Projection are the exact final topology and judgment.

Every public separate position is preserved below for continuity. Stevens's general private-deception position, O'Connor/Thomas's legal-enforceability objection, and O'Connor's individual statutory-precedent discussion are noncontrolling. No roster, allotment, companion or outside-case procedural change follows. The lower-court contract proceeding remains open; no new Supreme Court filing deadline is invented.

## Adaptive audit annex

| Associate | Frozen independent commitment | Reconciled commitment and controlling support | Final compatibility |
|---|---|---|---|
| Stevens | Preempt fraud; preserve confined contract. | Correct fraud to survival. His own Cipollone intentional-falsehood and promise analysis, and Morales's unadjudicated-claim limit, leave the premise for his historical distinction intact; no concrete changed premise supported the provisional contrary result. | Joins factual/posture and contract portions only; publishes the separate fraud disagreement. No majority reasoning about fraud is attributed to him. |
| O'Connor | Preempt fraud; preserve confined contract. | Correct contract to preemption. Her Morales join and the different ADA enact/enforce wording support dependence on legal enforceability; Cipollone's different wording does not remove that objection. Norfolk & Western supplies the contract-law point. | Fraud judgment only; authors dissent on contract. Her individual adherence discussion has no Thomas join. The external-policy limitation does not cure her objection. |
| Kennedy | Preempt fraud; preserve confined contract. | Retained. Morales plus his broader Cipollone common-law position permits the narrower actual-promise construction here. | Full join; no assumed construction defeating the reservation clause. |
| Souter | Same two-branch result. | Retained. Morales controls despite his nonparticipation; broader Cipollone position supports ordinary promise enforcement, not immunity for labels. | Full join with ordinary interpretation and defenses preserved. |
| Thomas | Preempt both branches. | Retained. Morales and his broader Cipollone express-preemption ground support clause-specific breadth. | Joins O'Connor's substantive enforcement analysis and disposition, not her independent statutory-precedent discussion. |
| Ginsburg | Preempt fraud; preserve confined contract. | Retained. Full ADA wording and limited Cipollone analogy support private ordering; O'Melveny bars assumed replacement federal contract law. | Author; no new federal contract regime or unrestricted implied-policy exception. |
| Breyer | Same two-branch result. | Retained. Independently applies Morales, the statute and actual-undertaking distinction. | Full join; no inherited Blackmun position or categorical every-cost rule. |

Scalia is not modeled or counted because he does not participate. Reconciliation corrects initial commitments before adjudication, not completed votes. No retained non-Stone judgment departure from the historical components remains. The historical overall 5–3 shorthand was rejected in favor of the two actual 7–1 and 6–2 components. Final partial joins are tested against the actual bounded portions above. No later same-day Allied-Bruce reasoning is an entering authority or source for O'Connor's writing. No material post-reconciliation associate change requires a new Stone-free audit.

## Source map and source qualifications

The [Illinois opinion](https://app.midpage.ai/document/wolens-v-american-airlines-inc-2035579) supplies the interlocutory route, damages branches, peripheral-effects reasoning and undisturbed injunction ruling. The [Records and Briefs collection](https://archive.org/details/micro_IA40385013_0492), briefs 08–09 as described in the neutral digest, supplies the reservation-of-change dispute and respective alleged credit restrictions; those OCR facts do not certify exact contractual quotations or final breach. The [official Code](https://www.govinfo.gov/content/pkg/USCODE-1994-title49/html/USCODE-1994-title49.htm) supports recodification and separate qualifications. The complete [official historical report](https://tile.loc.gov/storage-services/service/ll/usrep/usrep513/usrep513219/usrep513219.pdf), locally research/reconcile_b/219.pdf and .txt, supports comparator participation, split results, historical writings and dates, never the present assignment by itself. Source digest and reconciliation corrections control over unsupported paraphrase. Exact contractual language, an unpresented good-faith theory, a final damages award or a newly contested jurisdictional predicate would require additional scoped sources; none is adjudicated.

## Published separate positions retained for continuity

''' + W_SEPARATE + '\n\n## Validation and preservation\n\n' + COMMON_STATUS

record('American_Airlines_Inc_v_Wolens_merits_1995-01-18.md', 'American Airlines, Inc. v. Wolens; No. 93-1286.', 'Affirmed in part, reversed in part, and remanded; consumer-fraud preemption 7–1, confined contract survival 6–2; Scalia did not participate.', W_INTERNAL, {
 'Event': 'American Airlines, Inc. v. Wolens, No. 93-1286. Merits decision, January 18, 1995; argued November 1, 1994. On writ of certiorari to the Supreme Court of Illinois, reviewing its interlocutory ruling sustaining damages claims under the Illinois Consumer Fraud and Deceptive Business Practices Act and the airline\'s frequent-flyer agreement against federal preemption. The claims concern alleged devaluation of previously earned travel credits by 1988 redemption restrictions. The questions concern the two sources of obligation separately. Render form: full; the judgment has distinct component coalitions and partial opinion joins.',
 'Participation': "Chief Justice Stone-Zsela and Justices Stevens, O'Connor, Kennedy, Souter, Thomas, Ginsburg and Breyer participated. Justice Scalia took no part; no public reason is supplied.",
 'Public Action': 'The Court affirms in part, reverses in part and remands. The consumer-fraud damages branch is preempted; the contract branch may proceed only to enforce the actual private undertaking.',
 'Judgment & Remedy': W_JUDGMENT,
 'Opinion Topology': W_TOPOLOGY,
 'Holdings': W_HOLDINGS,
 'Precedent Treatment': 'Morales supplies the controlling airline-preemption rule while preserving remote effects and unresolved duties. Cipollone supplies the voluntary-source analogy without transferring its differently worded cigarette-law holdings wholesale. Norfolk & Western retains its railroad-law force; the fact that contracts require legal enforcement does not alone determine this airline clause\'s reach. No earlier precedent is overruled.',
 'Law After Decision': 'Effective January 18, 1995, the airline-preemption rule distinguishes these state-prescribed consumer-fraud obligations from enforcement confined to an airline\'s voluntary bargain. The contract question previously left open is now resolved within that limit. Ordinary formation, interpretation, defenses and remedies remain available to identify and enforce the agreement; external state policy cannot enlarge it. The May 1988 claims are governed by the transaction-period provisions. The 1994 recodification creates no additional holding, and no Alaska, airport-proprietor or property-transportation exception is invoked. The Court establishes no general immunity from state law and no replacement federal contract regime.',
 'Separate Writings': W_SEPARATE,
 'Procedure After Action': 'The cause returns to the Illinois courts after partial affirmance and partial reversal of the interlocutory judgment. The pleaded statutory consumer-fraud branch cannot proceed; the contract proceeding continues only within the private-undertaking boundary, including the meaning of American\'s change reservation, ordinary defenses and any proved remedy. The prior rejection of an injunction remains undisturbed. Supreme Court merits review ends; the Court makes no final liability, damages or precise blackout-date finding.',
 'Source Notes': 'The [Illinois Supreme Court opinion](https://app.midpage.ai/document/wolens-v-american-airlines-inc-2035579), 157 Ill. 2d 466, 626 N.E.2d 205, supplies the judgment under review. The [merits briefs](https://archive.org/details/micro_IA40385013_0492) describe the disputed reservation clause and treatment of credits; no exact contract quotation is necessary to the ruling. [Title 49 of the 1994 Code](https://www.govinfo.gov/content/pkg/USCODE-1994-title49/html/USCODE-1994-title49.htm) supplies the recodified passenger-preemption and savings provisions. Allegations about promise, breach and retroactive restrictions remain allegations, not adjudicated findings.'
}, {'participants':['Stone-Zsela','Stevens',"O'Connor",'Kennedy','Souter','Thomas','Ginsburg','Breyer'], 'nonparticipants':['Scalia'], 'components':[{'label':'fraud preemption','support':['Stone-Zsela',"O'Connor",'Kennedy','Souter','Thomas','Ginsburg','Breyer'],'oppose':['Stevens'],'count':'7-1'},{'label':'contract survival','support':['Stone-Zsela','Stevens','Kennedy','Souter','Ginsburg','Breyer'],'oppose':["O'Connor",'Thomas'],'count':'6-2'}], 'writings':[{'author':'Ginsburg','joins':['Stone-Zsela','Kennedy','Souter','Breyer'],'scope':'full; Stevens additionally factual/posture and contract only'},{'author':'Stevens','joins':[],'scope':'concurrence on contract, dissent on fraud'},{'author':"O'Connor",'joins':['Thomas'],'scope':'statutory-enforcement analysis and both-branch disposition; Thomas excludes separate statutory-precedent discussion'}], 'holding_coalitions':[{'label':'fraud preemption rationale','support':['Stone-Zsela','Kennedy','Souter','Ginsburg','Breyer']},{'label':'contract actual-undertaking rationale','support':['Stone-Zsela','Stevens','Kennedy','Souter','Ginsburg','Breyer']}]})

N_AUTH = "Justice Souter's Opinion of the Court, joined by Justices Stevens, O'Connor, Scalia, Kennedy, Thomas, Ginsburg and Breyer. Eight of nine participating Justices directly adopt this rule and its agency-review rationale. Chief Justice Stone-Zsela concurs in both judgments on an independent statutory ground and does not join this opinion."
N_HOLDINGS = '''#### Reasoned approval of annuity brokerage falls within the banking power

**Controlling proposition:** The business of banking under 12 U.S.C. §24 Seventh is not exhausted by its enumerated activities, and the Comptroller's reasonable construction may include financial-intermediary agency sales of the fixed, variable and combined annuity products covered by this approval. The construction must remain within banking and its incidental powers and comply with enacted restrictions; this conditioned brokerage approval authorizes no underwriting, issuance or guarantee of the insurers' obligations and no unrelated commercial enterprise.

**Authority:** ''' + N_AUTH + '''

**Controlling explanation:** The Court holds that the Act leaves room for a reasoned administrative judgment about financial services within banking. Section 24 Seventh identifies core activities but also grants the incidental powers necessary to carry on the business of banking. Clarke supplies specific support for substantial respect for the Comptroller's reasonable construction of that banking authority in the brokerage setting. Chevron requires courts first to enforce clear statutory boundaries; MCI and Gardner preserve that obligation rather than eliminating lawful interpretive discretion. Here the bank acts as agent between customers and insurers, offering financial instruments used for saving and investment. It does not issue the products or bear the insurer's actuarial or interest-rate risk. Camp requires genuine expert judgment, not a rationale invented by counsel, and the approval gives the relevant product and agency reasons. The contrary reading treats the enumerated activities as the entire banking business, overlooking the enacted broader language. The holding sustains this approval within its disclosure conditions, without authorizing every profitable financial activity or a bank's own-account underwriting.

**Precedent treatment:**

- Clarke v. Securities Industry Association, 479 U.S. 388: applies its substantial respect for reasonable Comptroller banking-law construction and brokerage analysis to this agency activity.
- Chevron U.S.A. Inc. v. Natural Resources Defense Council, Inc., 467 U.S. 837: applies deference within the ambiguity left after the enacted banking boundaries are determined; clear prohibitions still govern.
- Investment Company Institute v. Camp, 401 U.S. 617: preserves substantive banking restrictions and the need for an actual reasoned agency judgment, which this approval supplies.
- MCI Telecommunications Corp. v. American Telephone & Telegraph Co., 512 U.S. 218, and Brown v. Gardner, 513 U.S. 115: preserve text-first review and actual statutory limits; neither displaces permissible construction within a genuine delegation.

#### Section 92 does not defeat this annuity classification

**Controlling proposition:** The Comptroller reasonably classifies the annuity agency products covered by this approval as investment instruments outside the insurance category of 12 U.S.C. §92 for this statutory purpose, so §92 does not invalidate the approval. The Court does not decide whether §92 exclusively limits genuine insurance-agency activity to banks in qualifying small places, and it neither repeals that provision's conditions nor determines classification under a distinct state insurance law.

**Authority:** ''' + N_AUTH + '''

**Controlling explanation:** The Court holds that a product's label under other regulatory laws does not compel its classification under this banking provision. National Bank of Oregon establishes that §92 remains in force, but left its reach and the Comptroller's interpretation undecided. Deferred annuities can accumulate funds and permit lump-sum distribution or systematic withdrawal; variable products tie returns to selected investments. A lifetime payout option carries mortality risk, but it does not describe every use or feature of these instruments. The Comptroller therefore reasonably treated these agency sales as investment intermediation. Chevron and Clarke permit that bounded construction where Congress has not required the contrary classification. The Fifth Circuit inferred an exclusive geographic insurance prohibition from §92's specific small-place authorization and treated annuities categorically as insurance. The first inference need not be resolved because the second premise is not compelled. Section 92 begins by adding to existing powers; the Court leaves its application to true insurance sales intact. This judgment neither authorizes bank guarantees nor displaces any otherwise preserved state regulation.

**Precedent treatment:**

- United States National Bank of Oregon v. Independent Insurance Agents of America, Inc., 508 U.S. 439: applies the statutory-survival holding and respects its reservation of scope and agency-construction questions; no repeal issue is reopened.
- Chevron, 467 U.S. 837, and Clarke, 479 U.S. 388: apply permissible, reasoned construction to this statutory classification after examining the text and product features.

**Conditions and limits:** The Comptroller's approval separately requires advertising, promotional materials and customer descriptions to disclose that the annuities are not bank products and are not FDIC insured, together with a signed purchaser acknowledgment of agency status and lack of federal insurance. Brokerage does not issue, underwrite or guarantee an insurer's undertaking. Applicable banking, securities and insurance requirements otherwise remain.

When §92 applies, it requires the national bank to be located and doing business in a place of no more than 5,000 inhabitants under the last preceding decennial census; the insurer must be authorized by the State where the bank is located; and the agency must operate under Comptroller rules. It permits solicitation and sale of insurance and collection of premiums for agreed fees or commissions, but prohibits the bank from assuming or guaranteeing premium payment and separately prohibits guaranteeing the truth of the insured applicant's statements. Those statutory terms are not the same as this approval's disclosure conditions. Section 24's distinction between without-recourse, customer-order/customer-account securities transactions and own-account activity remains; no own-account investment exception is adjudicated. No individual customer's contract, universal annuity classification or separate state-law preemption dispute is resolved.'''

N_SEPARATE = '''Chief Justice Stone-Zsela concurs in the judgments in both dockets. He independently reads §24 Seventh to permit brokerage of financial investment products closely connected with banking. These annuities serve retirement saving and asset management, while the bank's agency role avoids underwriting the issuer's risk. The Comptroller's expertise and reasoned explanation are persuasive confirmation of the statutory fit; deference cannot supply a power the statute withholds. He does not join the Court's agency-deference rationale.

In his reading, §92's limited insurance authorization neither compels treating these annuities as insurance nor prohibits this incidental banking activity. He would reinstate the conditioned approval subject to applicable banking, securities and insurance rules. The approval gives no general power to underwrite insurance and displaces no state regulation preserved by federal law. His independent construction supplies his judgment votes, not a replacement for the eight-Justice controlling rationale.'''
N_INTERNAL = '''## Event, review, participation and law entering

NationsBank of North Carolina, N.A. v. Variable Annuity Life Insurance Co., No. 93-1612, and Ludwig v. Variable Annuity Life Insurance Co., No. 93-1613, consolidated. Argued December 7, 1994; decided January 18, 1995. Established merits review of the Fifth Circuit's August 26, 1993 judgment, 998 F.2d 1295, reversing the Southern District of Texas, 786 F. Supp. 639 (1991). A mirror's D.C.-Circuit metadata is erroneous; the judgment is Fifth Circuit. VALIC challenged the March 21, 1990 Comptroller approval of the bank subsidiary's agency sales of fixed, variable and combined annuities requested August 8, 1989. The statutory authority and §92 classification questions are reached. No invented jurisdictional or preservation obstacle, grant date or petition poll enters.

Chief Justice Stone-Zsela and Justices Stevens, O'Connor, Scalia, Kennedy, Souter, Thomas, Ginsburg and Breyer participate at both argument and decision; all were seated at argument. Nine participants satisfy the six-Justice quorum; five form a judgment or rationale majority. No case-specific nonparticipation or institutional change is established.

The relevant register “Antecedent governing law and nonpositive-law Code omissions,” effective National Bank of Oregon, June 7, 1993, establishes §92's survival, reserving geography and construction. “Limited modification authority and mandatory tariff filing,” effective MCI, June 17, 1994, preserves actual statutory limits, not an abolition of Chevron. Brown v. Gardner, December 12, 1994, requires statutory construction before deference; Transcon, January 10, 1995, preserves bounded enforcement authority, not automatic deference to litigation relief. Chevron, Clarke's banking-merits analysis and Camp supply surviving pre-divergence law. Thomas Jefferson University's own-regulation standard is not substituted for statutory review. No statutory command is inferred from the Fifth Circuit's geographic-exclusivity construction. The actual §24 banking/incidental-powers language and §92's full conditions are set out in the controlling holdings and limits.

## Stone fixed core, judgment-only agreement and assignment

The user authorized Section II as written. Stone independently interprets §24 Seventh, gives the Comptroller's explanation persuasive weight only, rejects treating §92 as a bar to this brokerage, and reverses both dockets subject to existing compliance conditions. This is materially distinct from the eight Associates' Chevron/Clarke rationale. His two judgment votes therefore do not become opinion joins, and his independent construction appears in a legally operative concurrence in the judgments. No deference ground is attributed to him; no majority common denominator is manufactured. His limits on underwriting, enacted powers and preserved state law are intact. No fallback is used. Correcting the Fifth-Circuit metadata and clarifying that reversal does not demand a new administrative explanation change no fixed core. The effective-law refresh finds no material new premise.

Stone belongs to both tentative judgment coalitions and assigns the Court opinion to Souter under Engine §8. Souter's earlier statutory-survival authorship makes a confined treatment of the reserved scope questions suitable to the governing coalition. Authorship is an assembly inference, not the historical author imported. Souter and all seven other Associates join both controlling holdings on the frozen grounds; Stone writes separately. Final judgment is 9–0 in each docket, with eight direct rationale votes. The judgment reverses rather than ordering a new agency remand. Ordinary implementation restores this conditioned approval against these objections; no new agency findings are demanded.

## Adaptive audit annex

| Associate | Independent commitment and final reconciled ground | Final join and preserved objection |
|---|---|---|
| Stevens | Reverse both; Clarke Parts I and III, which he joined, supports expert banking construction within Chevron after statutory boundaries are determined. Reconciliation retains both statutory propositions. | Full join; no unrelated enterprise, underwriting or guarantee, and no deference against clear text. |
| O'Connor | Reverse both; her Clarke merits join supports brokerage and leaves §92 classification distinct from survival. Retained. | Full join; approval conditions and genuine-insurance geographic question remain. |
| Scalia | Reverse both; §24 and the additional grant in §92 leave the interpretive room in which Clarke/Chevron operate; his MCI join preserves limits. Retained. | Full join; no expertise-based override or unstated own-account exception. |
| Kennedy | Reverse both; Clarke/Chevron and his MCI/Gardner positions support the actual functional administrative ground. Retained. | Full join; no counsel-created rationale and no own-regulation standard. |
| Souter | Reverse both; his National Bank of Oregon opinion left these questions open, and whole-statute reading permits the classification. Retained. | Author; no repeal reopening or general exclusivity holding. |
| Thomas | Reverse both; his MCI join requires genuine power, satisfied by this reasonable banking-intermediation construction. Retained. | Full join; a real banking connection remains essential. |
| Ginsburg | Reverse both; MCI/Gardner leave the actual delegated discretion supported by Clarke. Retained. | Full join; brokerage distinguished from issuing, underwriting and guaranteeing; no state-preemption ruling. |
| Breyer | Reverse both; independently applies savings/investment intermediation and optional payout features under Clarke/Chevron. Retained. | Full join; acknowledges mortality features and limits classification to the supplied approval. |

The contrary §92 exclusivity/category path and a new-agency-analysis remand were modeled before Stone entered. The former cannot compel this classification from one payout feature; the latter lacks an identified missing administrative ground on the supplied conditioned approval. Reconciliation clarified the initial “reverse and remand” shorthand to reversal of both judgments with ordinary implementation, not a new administrative remand. No Associate changes a vote or rationale after reconciliation and no Associate departure from the historical result remains. The difference in controlling coalition results solely from Stone's distinct fixed independent-reading ground; it is not a changed Associate premise. No hypothetical successful-adoption coalition is substituted.

## Continuity and sources

The two statutory holdings and preserved conditions control from January 18, 1995. Stone's independent construction is a published noncontrolling position retained for future continuity. No roster, allotment or companion change arises. Both Supreme Court merits matters are disposed of by reversal; any ordinary implementing proceedings must respect the conditioned approval, and no new deadline or remand-dependent agency finding is established.

The [Fifth Circuit opinion](https://openjurist.org/998/f2d/1295/variable-annuity-life-insurance-co-v-l-clarke-ncnb) supplies route, approval history, lower reasoning and agency role. The [primary briefs](https://archive.org/details/micro_IA40385013_0505), government 09 and respondent 10, and the government's reference to Pet. App. 35a–48a supply the digest's agency conditions; the initial source stage reviewed relevant portions rather than the entire appendix. The [official §24](https://www.govinfo.gov/content/pkg/USCODE-1994-title12/html/USCODE-1994-title12-chap2-subchapI-sec24.htm) and [official Title 12](https://www.govinfo.gov/content/pkg/USCODE-1994-title12/html/USCODE-1994-title12.htm) supply the statutory terms. The [complete official historical report](https://tile.loc.gov/storage-services/service/ll/usrep/usrep513/usrep513251/usrep513251.pdf), research/reconcile_b/251.pdf and .txt, supports comparator dates and unanimous historical rationale, not the present assignment or Stone join. No finding about an individual customer's contract or a new state insurance-law issue is supplied or inferred.

## Published separate position retained for continuity

''' + N_SEPARATE + '\n\n## Validation and preservation\n\n' + COMMON_STATUS

ALL = ['Stone-Zsela','Stevens',"O'Connor",'Scalia','Kennedy','Souter','Thomas','Ginsburg','Breyer']
ASSOCIATES = ALL[1:]
record('NationsBank_Ludwig_v_Variable_Annuity_Life_Insurance_Co_merits_1995-01-18.md', 'NationsBank of North Carolina, N.A. v. Variable Annuity Life Insurance Co., No. 93-1612; Ludwig v. Variable Annuity Life Insurance Co., No. 93-1613; consolidated.', 'Fifth Circuit reversed in both dockets, 9–0; eight-Justice Court opinion and Stone-Zsela concurrence in the judgments.', N_INTERNAL, {
 'Event': 'NationsBank of North Carolina, N.A. v. Variable Annuity Life Insurance Co., No. 93-1612, and Ludwig v. Variable Annuity Life Insurance Co., No. 93-1613, consolidated. Argued December 7, 1994; merits decision January 18, 1995. On writs of certiorari to the Fifth Circuit, reviewing 998 F.2d 1295, which reversed judgment for the Comptroller in a challenge to approval of annuity agency sales. The questions concern national-bank incidental powers under §24 Seventh and annuity classification under §92. Render form: full; unanimous judgments rest on an eight-Justice Court rationale and a distinct judgment-only concurrence.',
 'Participation': "Chief Justice Stone-Zsela and Justices Stevens, O'Connor, Scalia, Kennedy, Souter, Thomas, Ginsburg and Breyer participated at argument and decision.",
 'Public Action': 'The Court reverses the Fifth Circuit in both consolidated dockets, sustaining the Comptroller\'s conditioned approval against the statutory objections presented.',
 'Judgment & Remedy': "| Docket | Disposition and vote | Supporting Justices | Opposing Justices | Remedy |\n|---|---|---|---|---|\n| No. 93-1612, NationsBank | Reversed, 9–0 | Stone-Zsela, Stevens, O'Connor, Scalia, Kennedy, Souter, Thomas, Ginsburg, Breyer | No opposing vote | Conditioned agency approval sustained. |\n| No. 93-1613, Ludwig | Reversed, 9–0 | Stone-Zsela, Stevens, O'Connor, Scalia, Kennedy, Souter, Thomas, Ginsburg, Breyer | No opposing vote | Same conditioned agency approval sustained. |\n\nThe approval is reinstated subject to its disclosure and acknowledgment conditions and otherwise applicable banking, securities and insurance rules. The judgment requires no new administrative rationale or findings and authorizes no underwriting or bank guarantee.",
 'Opinion Topology': "| Writing | Author | Joined by | Relationship to judgment | Scope joined |\n|---|---|---|---|---|\n| Opinion of the Court | Souter | Stevens, O'Connor, Scalia, Kennedy, Thomas, Ginsburg, Breyer | Reversal in both dockets | Both statutory holdings and the confined agency-deference rationale, in full. |\n| Concurrence in the judgments | Stone-Zsela | No other Justice | Reversal in both dockets | Independent statutory construction; the agency's explanation is persuasive only. No join to the Court opinion. |",
 'Holdings': N_HOLDINGS,
 'Precedent Treatment': 'Clarke and Chevron govern reasonable banking-law construction within an actual delegation; Camp preserves enacted restrictions and genuine administrative reasoning. National Bank of Oregon settles §92\'s survival and leaves the present scope question open for decision. MCI and Gardner continue to require obedience to statutory boundaries; no general retreat from their text-first rule or from Chevron is adopted.',
 'Law After Decision': 'Effective January 18, 1995, the conditioned annuity agency business is permissible under the reasonable banking and classification constructions adopted by the Court. The listed banking activities do not exhaust the business of banking, but real banking bounds and express restrictions remain. Section 92\'s survival, small-place conditions and two prohibitions remain intact whenever that provision applies. The Court leaves broader insurance-agency geography, underwriting and separate state-law preemption unresolved. Stone-Zsela\'s independent statutory reading does not replace the controlling agency-review rationale.',
 'Separate Writings': N_SEPARATE,
 'Procedure After Action': 'Both Fifth Circuit judgments are reversed. Supreme Court merits review ends, and ordinary implementation must give effect to the Comptroller\'s existing conditioned approval. Advertising and customer disclosures, the signed purchaser acknowledgment and other applicable law remain conditions of operation. No new agency proceeding, individual contract recovery or additional business permission is ordered.',
 'Source Notes': 'The [Fifth Circuit opinion, 998 F.2d 1295](https://openjurist.org/998/f2d/1295/variable-annuity-life-insurance-co-v-l-clarke-ncnb), supplies the lower judgment and agency background. The [primary briefs and approval references](https://archive.org/details/micro_IA40385013_0505) identify the financial products and approval conditions. [Section 24](https://www.govinfo.gov/content/pkg/USCODE-1994-title12/html/USCODE-1994-title12-chap2-subchapI-sec24.htm) and [Title 12, including §92](https://www.govinfo.gov/content/pkg/USCODE-1994-title12/html/USCODE-1994-title12.htm), supply statutory text. No exact customer contract, customer-specific liability or underwriting approval is established.'
}, {'participants':ALL,'nonparticipants':[],'components':[{'label':'No. 93-1612 reversal','support':ALL,'oppose':[],'count':'9-0'},{'label':'No. 93-1613 reversal','support':ALL,'oppose':[],'count':'9-0'}], 'writings':[{'author':'Souter','joins':[j for j in ASSOCIATES if j!='Souter'],'scope':'Court opinion in full'},{'author':'Stone-Zsela','joins':[],'scope':'concurrence in both judgments, independent statutory reading only'}], 'holding_coalitions':[{'label':'banking and incidental power through permissible agency construction','support':ASSOCIATES},{'label':'permissible §92 annuity classification','support':ASSOCIATES}]})

A_AUTH = "Justice Breyer's Opinion of the Court, joined by Chief Justice Stone-Zsela and Justices Stevens, O'Connor, Kennedy, Souter and Ginsburg. Seven of nine participating Justices directly adopt this proposition and explanation. Justices Scalia and Thomas would affirm on the state-court ground and do not reach the alternative commerce questions."
A_HOLDINGS = '''#### Section 2 continues to govern covered agreements in state court

**Controlling proposition:** FAA §2 governs covered written arbitration agreements in state as well as federal court, making them valid, irrevocable and enforceable save upon grounds existing at law or equity for revocation of any contract. The Court retains Southland's state-court holding; Alabama may apply generally applicable contract defenses but may not deny enforcement solely because its law singles out predispute arbitration agreements for a categorical disability.

**Authority:** ''' + A_AUTH + '''

**Controlling explanation:** The Court holds that the established state-court application of §2 remains governing law. Southland supplies that substantive construction, and Perry confirms that a State cannot withhold enforcement by assigning a covered dispute to a judicial forum while preserving generally applicable contract defenses. Respondents and supporting States ask the Court to reject that interpretation in light of the Act's federal procedural structure. The statutory-construction objection deserves consideration, but repetition of that original disagreement does not establish a sufficient reason to overturn the settled rule and the reliance it permits across forums. Congress remains able to alter the statute. Alabama's categorical prohibition is directed at arbitration itself, not a defense to contracts generally. Volt does not save that prohibition: it enforces an actual contractual choice of state rules, and no such choice is established by the forum's location alone. Retaining §2's substantive command does not decide whether every direction in §§3 and 4 must operate identically in state courts or settle the assent and scope questions of every claim here.

**Precedent treatment:**

- Southland Corp. v. Keating, 465 U.S. 1: retains the substantive state-court application of §2 against the express request to overrule it; its commerce and general-contract-defense conditions remain.
- Perry v. Thomas, 482 U.S. 483: applies its rejection of a state judicial-forum exception directed at arbitration while preserving generally applicable contract defenses.
- Volt Information Sciences, Inc. v. Board of Trustees of Leland Stanford Junior University, 489 U.S. 468: preserves enforcement of an actual contractual choice of state arbitration rules; a forum-wide hostility to arbitration is not itself that choice.

#### Coverage turns on actual commerce within Congress's power

**Controlling proposition:** Section 2's phrase involving commerce reaches contracts evidencing transactions within the full commerce authority Congress constitutionally possesses, and coverage turns on the transaction's actual interstate commercial operation rather than whether the parties contemplated substantial interstate activity when contracting. The multistate service operations and interstate procurement of treatment and repair materials establish the necessary commerce here, requiring reversal of Alabama's coverage ruling; this statutory construction does not define the outer constitutional boundary or make remote interstate history alone conclusive.

**Authority:** ''' + A_AUTH + '''

**Controlling explanation:** The Court holds that §2 describes the transaction actually made and carried out. Its broad commerce language does not confine coverage to goods moving in an interstate stream, and its reference to a contract evidencing a transaction adds no private expectation or foresight requirement. Bernhardt preserves the need to show a transaction involving commerce; its failure-of-proof setting does not supply Alabama's contemplation test. Here a commercial termite-service arrangement involved firms operating across state lines and actual materials obtained outside Alabama. Local work on the house does not erase those commercial connections. The competing reading would make enforceability turn on what parties predicted about commerce instead of what their transaction involved, although Congress supplied no such mental-state condition. These facts establish genuine interstate commercial operation, rather than a talisman based on the remote history of one object. The ruling resolves statutory coverage under the commerce authority Congress possesses. It neither fixes that authority's furthest constitutional reach nor determines who agreed to arbitrate every pleaded claim or which ordinary contract defenses may succeed.

**Precedent treatment:**

- Bernhardt v. Polygraphic Co. of America, Inc., 350 U.S. 198: distinguishes a record failing to establish the requisite commerce; its transaction predicate survives, without a newly attributed contemplation requirement.
- Southland, 465 U.S. 1: applies its substantive enforceability rule after identifying the actual covered transaction; general hostility to arbitration does not substitute for the statutory commerce inquiry.

**Remedy and limits:** The Alabama Supreme Court judgment is reversed and the cause remanded under the actual-commerce rule. Formation, consent, fraud, duress, unconscionability, severability and other generally applicable contract defenses remain for ordinary adjudication to the extent properly presented and preserved below, together with party assent, clause scope and appropriate implementing procedure. Coverage is not a final order compelling all parties to arbitrate every claim. Section 1's separate employment exclusion is not presented by this service bond. The Court does not decide the tort merits, damages, a particular fraud-in-the-inducement defense, a contractual choice of state rules not established here, or wholesale state-court incorporation of §§3–4.'''

A_SEPARATE = '''Justice O'Connor joins the Court's opinion and concurs separately. She continues to believe that Southland originally misconstrued the Act's application in state courts, for the reasons set out in her Southland and Perry dissents. Statutory stare decisis nevertheless weighs strongly against reopening an interpretation that has governed for a decade without a demonstrated inability to administer it. Once that interpretation is retained, a broad and uniform actual-commerce rule is appropriate; narrowing commerce coverage is not a substitute for overruling Southland. Her original-construction reservation does not subtract from her join in the Court's present rule or mandate.

Justice Thomas dissents, joined by Justice Scalia. He reads the Act's structure and federal-court judicial directions as failing to create the substantive command to state courts that Southland announced. He would overrule Southland to that extent and affirm the denial of arbitration on the ground that the Act does not govern this state proceeding. He does not decide the alternative scope of commerce coverage or the factual success of a general contract defense. The dissent presents no additional independently sufficient specific-performance holding under §§3–4.

Justice Scalia also dissents separately. His earlier acceptance of Southland when its overruling was not requested does not resolve the express request presented here. In his view, reliance on a statutory interpretation cannot by itself preserve a state-court command the statute does not establish. He joins Thomas's state-court ground and would affirm without deciding the Court's commerce construction. These proposed changes to Southland do not control; the Court retains that precedent.'''

A_INTERNAL = '''## Event, participation and entering law

Allied-Bruce Terminix Cos. v. Dobson, No. 93-1001. Argued October 4, 1994; decided January 18, 1995. Established merits review of the Alabama Supreme Court's August 13, 1993 judgment, 628 So. 2d 354, affirming denial of a stay and motion to compel arbitration. The transaction is a 1987 termite-service bond transferred on sale of the Alabama house in 1991, followed by fraud and contract claims against the firms, claims against the sellers and the sellers' cross-claims. The firms are multistate businesses; materials were obtained from outside Alabama. No final merits findings are made. The precise municipality is omitted because the neutral digest and official background differ, without any material effect on the state's law, interstate facts or parties. No new grant date, poll, threshold objection or preservation finding is invented.

Chief Justice Stone-Zsela and Justices Stevens, O'Connor, Scalia, Kennedy, Souter, Thomas, Ginsburg and Breyer participate at argument and decision; nine participants satisfy the six-Justice quorum, and five are required for a majority. No nonparticipation, membership, seniority or allotment change arises.

FAA §2 contains its complete generally applicable revocation-defense qualification, reproduced in the Holdings rule. Southland supplies binding substantive state-court application unless reconsidered; respondents expressly request overruling on that ground. Perry preserves ordinary defenses and rejects arbitration-specific circumvention. Volt requires actual contractual choice, not the forum's hostility. Bernhardt preserves proof of commerce without establishing a foresight condition. Prima Paint's distinction between fraud in the arbitration clause and fraud in the whole contract in its federal setting is not converted into an unpresented defense ruling here. Section 1's employment exclusion is independent and untriggered; §§3–4's state-procedure reach is reserved. The focused/current and actual earlier-effective public-law copies supply no later FAA revision. No Mastrobuono, First Options, Lopez or Sky Reefer law enters the event.

## Stone fixed core and compatible participation

The user authorized Section II as written. Stone reaches the merits, holds that §2 reaches transactions within Congress's full constitutional commerce power and turns on actual rather than contemplated commerce, reverses Alabama and remands. He preserves ordinary formation and contract defenses for adjudication under ordinary law and distinguishes real interstate commercial operation from a talismanic object crossing a border. His reference to a future Lopez question is treated solely as a reservation of the constitutional ceiling, never an announcement of future law or prediction. No future authority appears in the public projection. The Court opinion adopts the actual-commerce rule and preserves that ceiling; his join neither treats the transaction predicate as automatic nor makes constitutional power unlimited.

His direction that the Alabama courts address contract issues under ordinary law operates subject to ordinary presentation and preservation; it supplies no new finding that each listed defense was asserted and no command to revive waived defenses. The Court's remand preserves that scope. Continued application of existing Southland/Perry is consistent with his instruction that the FAA applies to this state-court agreement; the Court's precedent treatment adds date-eligible support without altering his rule, result, remedy or limits. He joins the full Court opinion and publishes no unnecessary additional writing. No silent-component fallback is needed. The corrected city omission and Stevens/Perry source attribution affect no controlled Stone component. The actual pre-January-18 law creates no reapproval condition.

## Assignment, final coalition and continuity

Stone is in the reversal majority and assigns the opinion to Breyer under Engine §8. Breyer's frozen textual treatment of the actual transaction and preservation of general contract defenses fits the controlling coalition; authorship is selected in assembly rather than imposed by the historical comparator. Stevens, O'Connor, Kennedy, Souter and Ginsburg join with Stone and Breyer for seven on state-court retention, statutory breadth, actual-commerce coverage and reversal/remand. Scalia and Thomas oppose reversal on the state-court ground; they are not assigned affirmative votes for or against commerce propositions they do not reach. O'Connor's separate original-construction reservation is compatible with her present join through statutory stare decisis. Thomas and Scalia publish only their modeled state-court grounds; the additional historical specific-performance alternative is not adopted.

No fractured-rationale or Marks synthesis is needed. Southland retains force; the Court now rejects contemplated-commerce and stream-only limitations. Ordinary state proceedings must decide properly presented assent, scope and general defenses rather than treating coverage as final compulsion of every claim. O'Connor's original-construction disagreement and Scalia/Thomas's proposed rejection of state-court reach remain noncontrolling published positions. No additional external event, institutional change or final tort result follows. The decision supplies potential earlier law to later scheduled FAA matters only through a future effective-law refresh, not by predicting those results.

## Adaptive audit annex

| Associate | Frozen independent commitment | Reconciled result and Justice-specific basis | Final join boundary |
|---|---|---|---|
| Stevens | Retain state-court reach, broad actual commerce, reverse/remand. | Retained. His Southland agreement supports state-court reach despite his separately expressed room for substantive state policy; the supplied Perry-join attribution was corrected to a dissent. | Full join; categorical arbitration disability is not a generally applicable defense. No party-wide automatic compulsion. |
| O'Connor | Overrule Southland on state-court reach and affirm; no necessary commerce holding. | Correct to retention and reversal/remand. Her historical question-specific statutory-stare-decisis analysis confronted the same original objection; no new text, reliance failure, unworkability or simulated FAA change justified departure. | Full join through present adherence; separate original-reading reservation. She did not participate in Volt. |
| Scalia | Retain Southland, broad actual commerce, reverse/remand. | Correct to affirm on state-court nonapplication. His Perry/Volt joins did not answer an express request to overrule, which is present here; no changed premise supports retaining his provisional opposite vote. | Joins Thomas's bounded state-court dissent and writes on reconsideration; no commerce vote inferred. |
| Kennedy | Retain and reverse/remand under broad actual commerce. | Retained. His Volt join protects the agreement actually made; §2 has no foresight condition. | Full join; assent, scope and implementing procedure preserved. |
| Souter | Retain and reverse/remand under broad actual commerce. | Retained. Applies Southland/Perry and the objective transaction language; no personal earlier FAA opinion is invented. | Full join; local performance does not negate actual interstate operation. |
| Thomas | Retain and reverse/remand under broad actual commerce. | Correct to affirm. Statutory structure and the federal-court directions support his question-specific state-court objection; no material changed premise supports the initial contrary result. | Authors bounded state-court dissent; no unmodeled independent specific-performance alternative. |
| Ginsburg | Retain and reverse/remand under broad actual commerce. | Retained. Statutory stare decisis, objective text and Volt's actual-choice limit supply the ground. | Full join; genuine general defenses remain. |
| Breyer | Retain and reverse/remand under broad actual commerce. | Retained. Independently applies transaction language without a prediction condition and with the complete defense qualification. | Author; no predecessor position inherited and no immunity from general defenses. |

These corrections are pre-adjudication reconciliation, not revision of a completed result. All non-Stone final judgments match the historical judgment positions on materially unchanged premises. The final opinion does not move any Associate beyond the frozen rule's constitutional predicate or ordinary-defense limits. No post-reconciliation material commitment change or new Associate join occurs. Source correction: Stevens dissented in Perry, 482 U.S. 483, 493; no false majority join is repeated. Source boundary: the independent historical Thomas §§3–4 specific-performance argument was not validated in the neutral modeling; it is omitted as a ground, while the modeled general reservation of state procedure remains.

## Source map and qualifications

The [Alabama opinion](https://app.midpage.ai/document/allied-bruce-terminix-v-dobson-1662045) supplies the denial, contemplation rationale and transaction evidence. The [primary briefs](https://archive.org/details/micro_IA40385013_0479), petitioners 07 and respondents 08, supply the reported alternatives, including the request to overrule Southland and States' position; the source digest reports pertinent-section review, not a full appendix review. The [official §2](https://www.govinfo.gov/content/pkg/USCODE-1994-title9/html/USCODE-1994-title9-chap1-sec2.htm) supplies the complete savings language. [Southland](https://www.law.cornell.edu/supremecourt/text/465/1), [Perry](https://www.law.cornell.edu/supremecourt/text/482/483) and [Volt](https://www.law.cornell.edu/supremecourt/text/489/468) supply date-eligible earlier authority. The complete [official historical report](https://tile.loc.gov/storage-services/service/ll/usrep/usrep513/usrep513265/usrep513265.pdf), research/reconcile_b/265.pdf and .txt, supplies comparator review, source correction and historical dates, not an automatic present assignment. Exact clause scope, party-specific assent and particular defenses require their ordinary record treatment below; this coverage ruling does not fill them.

## Published separate positions retained for continuity

''' + A_SEPARATE + '\n\n## Validation and preservation\n\n' + COMMON_STATUS

A_MAJ = ['Stone-Zsela','Stevens',"O'Connor",'Kennedy','Souter','Ginsburg','Breyer']
record('Allied_Bruce_Terminix_Cos_v_Dobson_merits_1995-01-18.md', 'Allied-Bruce Terminix Cos. v. Dobson; No. 93-1001.', 'Alabama Supreme Court reversed and remanded, 7–2; Scalia and Thomas would affirm on state-court nonapplication.', A_INTERNAL, {
 'Event': 'Allied-Bruce Terminix Cos. v. Dobson, No. 93-1001. Argued October 4, 1994; merits decision January 18, 1995. On writ of certiorari to the Supreme Court of Alabama, reviewing 628 So. 2d 354, which affirmed denial of a stay and motion to compel arbitration in a dispute concerning a transferred termite-service bond. The questions concern FAA §2\'s state-court application, the breadth of involving commerce and the requirement of actual rather than contemplated interstate activity. Render form: full; the state-court and commerce holdings are distinct, and the dissenters do not reach the commerce alternatives.',
 'Participation': "Chief Justice Stone-Zsela and Justices Stevens, O'Connor, Scalia, Kennedy, Souter, Thomas, Ginsburg and Breyer participated at argument and decision.",
 'Public Action': 'The Court reverses and remands. Section 2 continues to apply in state court, and this transaction falls within its commerce coverage without a requirement that the parties contemplated substantial interstate activity.',
 'Judgment & Remedy': "| Judgment component | Disposition and vote | Supporting Justices | Opposing Justices | Remedy |\n|---|---|---|---|---|\n| Denial of the arbitration request under the state-court and contemplated-commerce grounds | Reverse and remand, 7–2 | Stone-Zsela, Stevens, O'Connor, Kennedy, Souter, Ginsburg, Breyer | Scalia, Thomas | Apply §2 to the actual transaction; address properly presented assent, scope, general contract defenses and implementing procedure. |\n\nScalia and Thomas would affirm because the Act does not govern state proceedings in their view; they do not decide the alternative commerce questions. Reversal establishes statutory coverage, not final tort liability or automatic compulsion of every party and claim.",
 'Opinion Topology': "| Writing | Author | Joined by | Relationship to judgment | Scope joined |\n|---|---|---|---|---|\n| Opinion of the Court | Breyer | Stone-Zsela, Stevens, O'Connor, Kennedy, Souter, Ginsburg | Reversal and remand | In full, including state-court retention, commerce rule and general-defense limits. |\n| Concurrence | O'Connor | No other Justice | Joins the Court | Explains adherence to Southland despite disagreement with its original reading. |\n| Dissent | Thomas | Scalia | Would affirm | State-court nonapplication; no alternative commerce decision or independent specific-performance ground. |\n| Separate dissent | Scalia | No other Justice | Would affirm; also joins Thomas | Explains why prior adherence did not settle an express request to overrule Southland. |",
 'Holdings': A_HOLDINGS,
 'Precedent Treatment': 'Southland\'s substantive application in state court is retained, and Perry continues to reject arbitration-specific state barriers while preserving ordinary contract defenses. Volt protects an actual choice of state rules, not an assumed adoption of the forum\'s antiarbitration policy. Bernhardt retains the commerce predicate but supplies no contemplation requirement. No earlier decision is overruled, and §§3–4\'s entire state-procedure reach is not decided.',
 'Law After Decision': 'Effective January 18, 1995, §2 reaches actual transactions within Congress\'s constitutional commerce power without subjective contemplation or a stream-only limitation. State courts remain bound by its substantive enforceability rule and full general-contract-defense qualification. The genuine multistate operations and interstate materials suffice here; the outer constitutional ceiling, every party\'s assent, clause scope and particular contract defenses remain for their proper settings. The decision adds no special immunity from ordinary contract law.',
 'Separate Writings': A_SEPARATE,
 'Procedure After Action': 'The Alabama Supreme Court judgment is reversed and the cause remanded. The state courts must apply the actual-commerce rule and address formation, consent, fraud, duress, unconscionability, severability and other ordinary contract issues insofar as properly presented and preserved, as well as clause scope and implementing procedure. No waived defense is revived, final damages ordered or universal party-by-party arbitration order entered. Supreme Court merits review ends; the arbitration request and underlying litigation continue below within these limits.',
 'Source Notes': 'The [Alabama Supreme Court opinion](https://app.midpage.ai/document/allied-bruce-terminix-v-dobson-1662045), 628 So. 2d 354, supplies the judgment and contemplated-commerce reasoning. The [briefs](https://archive.org/details/micro_IA40385013_0479) identify the interstate features and alternatives concerning state-court reach. [FAA §2](https://www.govinfo.gov/content/pkg/USCODE-1994-title9/html/USCODE-1994-title9-chap1-sec2.htm) supplies the complete generally applicable contract-defense qualification. No exact municipality, final party-specific assent finding or resolved contract defense is necessary to the statutory coverage holding.'
}, {'participants':ALL,'nonparticipants':[],'components':[{'label':'reverse and remand arbitration denial','support':A_MAJ,'oppose':['Scalia','Thomas'],'count':'7-2'}], 'writings':[{'author':'Breyer','joins':[j for j in A_MAJ if j!='Breyer'],'scope':'full Court opinion'},{'author':"O'Connor",'joins':[],'scope':'statutory stare decisis concurrence'},{'author':'Thomas','joins':['Scalia'],'scope':'state-court dissent only; no independent specific-performance alternative'},{'author':'Scalia','joins':[],'scope':'separate state-court reconsideration dissent'}], 'holding_coalitions':[{'label':'state-court §2 retention','support':A_MAJ},{'label':'full constitutional statutory reach and actual-commerce test','support':A_MAJ,'not_reached':['Scalia','Thomas']}]})

# Deterministic consistency only. Legal meaning and coalitions are authored above.
for v in VOTES:
    participants = set(v['participants'])
    for c in v['components']:
        assert set(c['support']).isdisjoint(c['oppose'])
        assert set(c['support']) | set(c['oppose']) == participants
        assert c['count'] == f"{len(c['support'])}-{len(c['oppose'])}"
    for h in v['holding_coalitions']:
        assert len(h['support']) >= len(participants)//2+1
        assert set(h['support']) <= participants
    p = DRAFTS / v['filename']
    t = p.read_text(encoding='utf-8')
    expected = ['**Case and dockets:**','**Event and date:**','**Result:**','**Version / lineage:**']
    assert all(line.startswith(label) for line,label in zip(t.splitlines(),expected))
    pub = t.split('## Public Projection\n\n',1)[1]
    assert re.findall(r'^## (.+)$',pub,re.M) == BLOCKS
    internal_holdings = t.split('## Controlling holdings\n\n',1)[1].split('\n\n## Public Projection',1)[0]
    public_holdings = pub.split('## Holdings\n\n',1)[1].split('\n\n## Precedent Treatment',1)[0]
    assert internal_holdings == public_holdings
    lengths = [len(x.split()) for x in re.findall(r'\*\*Controlling explanation:\*\* (.*?)(?=\n\n\*\*Precedent treatment:)', public_holdings, re.S)]
    assert all(120<=n<=200 for n in lengths), (v['filename'],lengths)
    assert not any(bad in pub for bad in ['PENDING_PRE_JAN18','historical comparator','Git','Section II','simulated','approved','Lopez'])
    print(v['filename'], 'PASS', 'explanation words', lengths)
(ROOT / 'freeze' / 'OT_1994CHUNK2_VOTES_B.json').write_text(json.dumps(VOTES,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
